const tokens = [
  {
    urls: {
      chat: "https://www.dextools.io/app/en/solana/pair-explorer/BFz8kSfCCc6mmXmfnstCNgNuNXtPZ1ZMAxLokE7M6MvH?t=1712759981926",
      announcement: "https://nubcat.xyz/",
      website: "https://nubcat.xyz/",
      source_code: "",
      doxx: "",
      kyc: "",
      audit: "",
      telegramContact: "https://t.me/tonguecatluis",
      twitter: "https://twitter.com/TongueCatLuis2",
      launchpadURL:
        "https://www.dextools.io/app/en/solana/pair-explorer/BFz8kSfCCc6mmXmfnstCNgNuNXtPZ1ZMAxLokE7M6MvH?t=1712759981926",
      explorer: "https://nubcat.xyz/",
      telegram: "https://t.me/tonguecatluis",
      safu: "",
      launchpad: "Dextool",
    },
    votes: 100,
    bmc_audit_score: null,
    max_supply: null,
    category: null,
    tags: ["Tongue Cat", "LUIS"],
    verified: true,
    date_launched: 1712759973000,
    date_added: 1712761226718,
    notice: null,
    platform: "solana",
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/LUIS%2FTongue%20Cat%2F1.jpg5c34d8ce-f1ac-4e19-b5d8-23577308419b?alt=media&token=27fc3062-7a7d-482c-8986-f2db389220ab",
    symbol: "LUIS",
    contract_address: "5wU4tUcAbds7d5cmnGK2otHa9gbayYsD2mhz1reR6c91",
    id: "tonguecat303",
    subreddit: null,
    quote: null,
    total_supply: null,
    coinName: "Tongue Cat",
    infinite_supply: null,
    bmc_audit: false,
    approved: true,
    presale: false,
    slug: "tongue cat",
    date_end: 1712759973000,
    cmc_id: null,
    description:
      "Tongue Cat $LUIS is nothing but a cute kitten in a skin care session with his tongue out in Solana Blockchain.\n\n",
  },
  {
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/EGG%2FJustAnEgg%2F1.jpg451553d0-b667-4860-a430-d4985b82ef6d?alt=media&token=8914f7af-0abe-473f-909e-c45519472cd6",
    notice: null,
    quote: null,
    bmc_audit_score: null,
    id: "justanegg305",
    total_supply: null,
    cmc_id: null,
    platform: "solana",
    category: null,
    infinite_supply: null,
    approved: false,
    urls: {
      kyc: "",
      audit: "",
      twitter: "https://twitter.com/justaneggcoin",
      safu: "",
      launchpadURL:
        " https://www.dextools.io/app/en/solana/pair-explorer/BUPTMMrUnfeE5mk6L6ZUgrHtZo2qyeR44s9L6UGg1oQB?t=1712775496322",
      chart:
        " https://www.dextools.io/app/en/solana/pair-explorer/BUPTMMrUnfeE5mk6L6ZUgrHtZo2qyeR44s9L6UGg1oQB?t=1712775496322",
      website: "https://justanegg.com/",
      doxx: "",
      telegramContact: "https://t.me/JustAnEggSol",
      explorer: "https://justanegg.com/",
      source_code: "",
      telegram: "https://t.me/JustAnEggSol",
      announcement: "https://justanegg.com/",
      launchpad: "DEXTOOL",
    },
    max_supply: null,
    presale: false,
    subreddit: null,
    date_added: 1712775971240,
    slug: "justanegg",
    symbol: "EGG",
    description:
      "Imagine if your breakfast winked back and turned into crypto. JustAnEgg!\nNot your average egg pun factory; we're here to fry up the crypto game and poach the top spot among meme coins. Serious security with a side of laughs. Join us, and let’s make web culture egg-straordinary!",
    date_launched: 1712775677000,
    votes: 100,
    verified: true,
    date_end: 1712775677000,
    bmc_audit: false,
    contract_address: "wo1zgt8rfrYpvdVi4nidoj1SYfcR4pQx69bmNv2JLhQ",
    coinName: "JustAnEgg",
    tags: ["JustAnEgg", "EGG"],
  },
  {
    max_supply: null,
    subreddit: null,
    votes: 100,
    description: "The (second) most memeable dog on solana\n",
    notice: null,
    platform: "solana",
    symbol: "jotch",
    id: "jotchua306",
    urls: {
      launchpadURL:
        "https://www.dextools.io/app/en/solana/pair-explorer/EHByX2eQyA7aR9dNNT8e8FKr2ALyVQmzpMaoHcWUhNiG?t=1712777014498",
      launchpad: "Dextool",
      doxx: "",
      website: "https://www.jotchuaonsol.com/",
      telegramContact: "https://t.me/jotchualol",
      audit: "",
      source_code: "",
      twitter: "https://twitter.com/JotchOnSol",
      chart:
        "https://www.dextools.io/app/en/solana/pair-explorer/EHByX2eQyA7aR9dNNT8e8FKr2ALyVQmzpMaoHcWUhNiG?t=1712777014498",
      explorer: "https://www.jotchuaonsol.com/",
      safu: "",
      kyc: "",
      telegram: "https://t.me/jotchualol",
      announcement: "https://www.jotchuaonsol.com/",
    },
    tags: ["Jotchua", "jotch"],
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/jotch%2FJotchua%2F1.jpg3043a515-2802-4a5a-a117-c1fcbe5a00b1?alt=media&token=59089d43-f4e7-4649-a97a-f890febfba3f",
    date_launched: 1712776896000,
    bmc_audit_score: null,
    date_added: 1712777064385,
    total_supply: null,
    verified: true,
    presale: false,
    cmc_id: null,
    bmc_audit: false,
    coinName: "Jotchua",
    quote: null,
    category: null,
    approved: false,
    date_end: 1712776896000,
    infinite_supply: null,
    contract_address: "6ktDB8pro2WTCW1WkuevBWs4Jm4B9Y11iJL6TLvmEBey",
    slug: "jotchua",
  },
  {
    contract_address: "69SEPKGCzFzJLoSawb3xPfcqnZdiVm21Xu28AWZB5pzk",
    tags: ["JizzLord ", "JIZZLORD"],
    category: null,
    votes: 100,
    platform: "solana",
    id: "jizzlord308",
    presale: false,
    infinite_supply: null,
    date_launched: 1712788878000,
    date_end: 1712788878000,
    notice: null,
    approved: true,
    cmc_id: null,
    coinName: "JizzLord ",
    total_supply: null,
    description:
      "Unlock exclusive presale access and promotions with the coin that powers Black Arrow Launchpad – the exclusive Presale launchpad with a record success rate. JizzLord reached a 69x return for presales buyers (seriously – 69).\n\nFind us on a Dex, MEXC or LBank (more on the way!)",
    verified: true,
    symbol: "JIZZLORD",
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/JIZZLORD%2FJizzLord%20%2F1.jpg8ec047e9-ea1b-43fb-9661-af8c5430f59c?alt=media&token=ae62422a-0a74-4dc8-9c7a-9bc0c569e447",
    bmc_audit: false,
    subreddit: null,
    bmc_audit_score: null,
    quote: null,
    date_added: 1712789034732,
    urls: {
      doxx: "",
      twitter: "https://twitter.com/jizzlordcoin",
      launchpad: "MEXC",
      telegram: "https://t.me/+sOW5z6c4oV04NTlk",
      source_code: "",
      chart: "https://www.mexc.com/exchange/JIZZLORD_USDT",
      website: "https://jizzlordcoin.com/",
      audit: "",
      launchpadURL: "https://www.mexc.com/exchange/JIZZLORD_USDT",
      safu: "",
      explorer: "https://jizzlordcoin.com/",
      telegramContact: "https://t.me/+sOW5z6c4oV04NTlk",
      announcement: "https://jizzlordcoin.com/",
      kyc: "",
    },
    slug: "jizzlord ",
    max_supply: null,
  },
  {
    category: null,
    notice: null,
    bmc_audit_score: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/TRUF%2FTruflation%20%2F1.jpg1563d730-8c3b-4629-9e0d-c217438ba677?alt=media&token=e80d42ac-0c06-4041-b215-1f8513d4c8eb",
    verified: true,
    quote: null,
    max_supply: null,
    date_launched: 1712790140000,
    id: "truflation309",
    coinName: "Truflation ",
    cmc_id: null,
    contract_address: "0x38c2a4a7330b22788374b8ff70bba513c8d848ca",
    approved: true,
    infinite_supply: null,
    urls: {
      kyc: "",
      doxx: "",
      announcement: "https://truflation.com/",
      chart: "https://www.kucoin.com/trade/TRUF-USDT",
      launchpadURL: "https://www.kucoin.com/trade/TRUF-USDT",
      audit: "",
      safu: "",
      twitter: "https://twitter.com/truflation",
      launchpad: "KUCOIN",
      source_code: "",
      telegram: "https://t.me/truflation",
      telegramContact: "https://t.me/truflation",
      website: "https://truflation.com/",
      explorer: "https://truflation.com/",
    },
    tags: ["Truflation ", "TRUF"],
    presale: false,
    votes: 100,
    subreddit: null,
    symbol: "TRUF",
    description:
      "Backed by Coinbase and Chainlink, Truflation is a leading DRP (definite reference point protocol) for economic truth that is powering the tokenization of Real World Assets with its independent, transparent, and real-time financial data. Tracking over 13 million items, Truflation’s censorship-resistant and accessible data indexes provide the necessary data infrastructure to bring about systemic advancements in the DeFi economy, empowering dApps like DEXs to open limitless markets. ",
    date_end: 1712790140000,
    bmc_audit: false,
    slug: "truflation ",
    total_supply: null,
    platform: "ethereum",
    date_added: 1712790442371,
  },
  {
    subreddit: null,
    coinName: "Tensor ",
    tags: ["Tensor ", "TNSR"],
    cmc_id: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/TNSR%2FTensor%20%2F1.jpg3f72521a-6959-4ad2-9c66-425db312db12?alt=media&token=07b30f52-c9d6-46f8-877b-c12f1e6c6e91",
    presale: false,
    symbol: "TNSR",
    votes: 100,
    contract_address: "TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6",
    quote: null,
    bmc_audit: false,
    urls: {
      telegram: "https://discord.gg/tensor",
      kyc: "",
      source_code: "",
      twitter: "https://twitter.com/tensorfdn",
      announcement: "https://discord.gg/tensor",
      audit: "",
      safu: "",
      launchpad: "KUCOIN",
      telegramContact: "https://discord.gg/tensor",
      chart: "https://www.kucoin.com/trade/TNSR-USDT",
      doxx: "",
      website: "https://discord.gg/tensor",
      explorer: "https://discord.gg/tensor",
      launchpadURL: "https://www.kucoin.com/trade/TNSR-USDT",
    },
    infinite_supply: null,
    verified: true,
    bmc_audit_score: null,
    category: null,
    description:
      "Tensor Foundation facilitates community-led governance over Tensor protocols and helps the Tensor DAO grow and develop the Tensor ecosystem.\n\nTensor protocols are critical trading infrastructure for NFTs built on Solana — one of the only chains with the throughput, speed, and low fees necessary for mass adoption.",
    id: "tensor310",
    platform: "solana",
    date_added: 1712791699436,
    date_launched: 1712791468000,
    max_supply: null,
    notice: null,
    total_supply: null,
    approved: true,
    date_end: 1712791468000,
    slug: "tensor ",
  },
  {
    description:
      "Bitcoin to Solana Made Seamless\nCross-Chain Communication Layer Built on SVM.",
    approved: true,
    category: null,
    verified: true,
    presale: false,
    id: "zeusnetwork312",
    contract_address: "ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq",
    infinite_supply: null,
    date_end: 1712827542000,
    cmc_id: null,
    date_launched: 1712827542000,
    date_added: 1712827711184,
    coinName: "Zeus Network ",
    bmc_audit_score: null,
    max_supply: null,
    quote: null,
    total_supply: null,
    bmc_audit: false,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/ZEUS%2FZeus%20Network%20%2F1.jpgac22ccd2-d7f6-4ee5-b26d-dbcd9d9e1d33?alt=media&token=57600e2e-ba38-45af-b464-b4095b27e99f",
    urls: {
      launchpadURL: "https://www.gate.io/trade/ZEUS_USDT",
      launchpad: "GATEIO",
      source_code: "",
      kyc: "",
      telegramContact: "https://discord.com/invite/zeusnetwork",
      announcement: "https://zeusnetwork.xyz/",
      explorer: "https://zeusnetwork.xyz/",
      twitter: "https://twitter.com/ZeusNetworkHQ",
      safu: "",
      doxx: "",
      chart: "https://www.gate.io/trade/ZEUS_USDT",
      telegram: "https://discord.com/invite/zeusnetwork",
      website: "https://zeusnetwork.xyz/",
      audit: "",
    },
    votes: 100,
    symbol: "ZEUS",
    subreddit: null,
    platform: "solana",
    notice: null,
    tags: ["Zeus Network ", "ZEUS"],
    slug: "zeus network ",
  },
  {
    bmc_audit_score: null,
    approved: true,
    platform: "solana",
    urls: {
      launchpad: "Binance",
      doxx: "",
      audit: "",
      telegram: "https://t.me/wormholecrypto",
      announcement: "https://wormhole.com",
      website: "https://wormhole.com",
      launchpadURL:
        "https://www.binance.com/en/trade/W_USDT?ref=40896146&type=spot",
      safu: "",
      explorer: "https://wormhole.com",
      kyc: "",
      source_code: "",
      telegramContact: "https://t.me/wormholecrypto",
      twitter: "https://twitter.com/wormhole",
      chart: " https://www.binance.com/en/trade/W_USDT?ref=40896146&type=spot",
    },
    verified: true,
    cmc_id: null,
    subreddit: null,
    symbol: "Wormhole ",
    date_added: 1712828129699,
    slug: "wormhole ",
    bmc_audit: false,
    date_launched: 1712827928000,
    id: "wormhole314",
    category: null,
    description:
      "Hundreds of companies and applications use Wormhole’s blockchain connectivity platform to securely and scalably grow their user base, increase market share, and drive more on-chain activity.\n\n",
    notice: null,
    max_supply: null,
    total_supply: null,
    quote: null,
    infinite_supply: null,
    presale: false,
    tags: ["Wormhole ", "Wormhole "],
    date_end: 1712827928000,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/Wormhole%20%2FWormhole%20%2F1.jpgbdb09302-d0a9-49d4-b0d1-d028ce437aa0?alt=media&token=32b112b9-da00-40e2-88eb-d783e794cb49",
    votes: 100,
    coinName: "Wormhole ",
    contract_address: "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
  },
  {
    symbol: "SQR",
    platform: "bsc",
    category: null,
    contract_address: "0x2B72867c32CF673F7b02d208B26889fEd353B1f8",
    date_added: 1712873411678,
    date_end: 1712873239000,
    bmc_audit: false,
    max_supply: null,
    date_launched: 1712873239000,
    votes: 100,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/SQR%2FMagic%20Square%20%2F1.pngaa2449ba-29f9-469f-b6e4-a81452099052?alt=media&token=8b021a56-d1ea-44ea-98e2-8a13caf246d5",
    infinite_supply: null,
    description:
      "Magic Square is an immersive Discovery & Engagement Platform for the Web3 Crypto Ecosystem, empowering users to explore a wide array of community-vetted apps and games. Discover exciting rewards, engaging giveaways, and unlock incredible use-to-earn opportunities within our platform.\n\n",
    subreddit: null,
    approved: true,
    slug: "magic square ",
    quote: null,
    bmc_audit_score: null,
    total_supply: null,
    urls: {
      launchpadURL: "https://www.kucoin.com/trade/SQR-USDT?rcode=rPH7VCS",
      audit: "",
      telegram: "https://t.me/magicsquare_official",
      announcement: "https://magicsquare.io/",
      website: "https://magicsquare.io/",
      doxx: "",
      kyc: "",
      explorer: "https://magicsquare.io/",
      source_code: "",
      telegramContact: "https://t.me/magicsquare_official",
      safu: "",
      twitter: "https://twitter.com/MagicSquareio",
      chart: "https://www.kucoin.com/trade/SQR-USDT?rcode=rPH7VCS",
      launchpad: "Kucoin",
    },
    id: "magicsquare323",
    verified: true,
    presale: false,
    cmc_id: null,
    tags: ["Magic Square ", "SQR"],
    coinName: "Magic Square ",
    notice: null,
  },
  {
    date_end: 1712792375000,
    id: "aerodromefinance311",
    category: null,
    quote: null,
    tags: ["Aerodrome Finance ", "AERO"],
    coinName: "Aerodrome Finance ",
    notice: null,
    verified: true,
    infinite_supply: null,
    cmc_id: null,
    bmc_audit_score: null,
    approved: true,
    date_added: 1712792505121,
    bmc_audit: false,
    platform: "base",
    contract_address: "0x940181a94a35a4569e4529a3cdfb74e38fd98631",
    max_supply: null,
    total_supply: null,
    urls: {
      launchpadURL: "https://www.kucoin.com/trade/AERO-USDT",
      telegram: "https://discord.gg/aerodrome",
      audit: "",
      kyc: "",
      doxx: "",
      source_code: "",
      announcement: "https://aerodrome.finance/",
      explorer: "https://aerodrome.finance/",
      telegramContact: "https://discord.gg/aerodrome",
      chart: "https://www.kucoin.com/trade/AERO-USDT",
      twitter: "https://twitter.com/aerodromefi",
      website: "https://aerodrome.finance/",
      safu: "",
      launchpad: "KUCOIN",
    },
    description:
      "Aerodrome Finance is a next-generation AMM designed to serve as Base's central liquidity hub, combining a powerful liquidity incentive engine, vote-lock governance model, and friendly user experience. Aerodrome inherits the latest features from Velodrome V2. Aerodrome NFTs vote to distribute token emissions and receive incentives and fees generated by the protocol.\n",
    symbol: "AERO",
    date_launched: 1712792375000,
    presale: false,
    votes: 100,
    subreddit: null,
    slug: "aerodrome finance ",
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/AERO%2FAerodrome%20Finance%20%2F1.jpg6221b953-7f24-4020-ab04-a778e7e50700?alt=media&token=195c4d08-811f-49ec-ac7f-c4121b78c4d1",
  },
  {
    coinName: "Foxy ",
    symbol: "Foxy ",
    votes: 100,
    notice: null,
    urls: {
      telegramContact: "https://t.me/WeLikeTheFox",
      explorer: "https://www.welikethefox.io/",
      safu: "",
      audit: "",
      launchpadURL: "https://www.kucoin.com/trade/FOXY-USDT?rcode=rPH7VCS",
      telegram: "https://t.me/WeLikeTheFox",
      kyc: "",
      source_code: "",
      chart: "https://www.kucoin.com/trade/FOXY-USDT?rcode=rPH7VCS",
      doxx: "",
      twitter: "https://twitter.com/foxylinea",
      announcement: "https://www.welikethefox.io/",
      website: "https://www.welikethefox.io/",
      launchpad: "Kucoin",
    },
    approved: false,
    total_supply: null,
    cmc_id: null,
    date_end: 1712969566000,
    category: null,
    bmc_audit: false,
    verified: true,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/Foxy%20%2FFoxy%20%2F11.jpg921b2e08-a1f1-47f3-96c1-0325e716ad50?alt=media&token=cda46170-6dcf-42bd-8030-9ec6ca2d7fa5",
    tags: ["Foxy ", "Foxy "],
    platform: "tba",
    infinite_supply: null,
    subreddit: null,
    description:
      "Foxy is a mascot token for the Linea blockchain. Foxy is a culture coin, a meme token for the users of the Linea blockchain to rally behind, and help build a sense of community.\n",
    date_added: 1712969686075,
    max_supply: null,
    bmc_audit_score: null,
    contract_address: "0x5FBDF89403270a1846F5ae7D113A989F850d1566",
    date_launched: 1712969566000,
    id: "foxy335",
    quote: null,
    presale: false,
    slug: "foxy ",
  },
  {
    category: null,
    date_end: 1713075604000,
    symbol: "flok",
    contract_address: "CgHfihuKnP9RrsDDZBcwKdgVtzCfTFecY5Bnhpa7qTov",
    urls: {
      kyc: "",
      safu: "",
      telegram: "https://t.me/FLOKCTO",
      announcement: "https://flokonsol.com",
      source_code: "",
      chart:
        "https://dexscreener.com/solana/CgHfihuKnP9RrsDDZBcwKdgVtzCfTFecY5Bnhpa7qTov",
      website: "https://flokonsol.com",
      explorer: "https://flokonsol.com",
      launchpad: "raydium",
      doxx: "",
      telegramContact: "https://t.me/bip_3_9",
      audit: "",
      twitter: "https://twitter.com/FlokOnSol",
      launchpadURL:
        "https://raydium.io/swap/?inputCurrency=sol&outputCurrency=CgHfihuKnP9RrsDDZBcwKdgVtzCfTFecY5Bnhpa7qTov&fixed=in",
    },
    verified: true,
    slug: "flok",
    subreddit: null,
    coinName: "Flok",
    presale: false,
    votes: 100,
    id: "flok347",
    infinite_supply: null,
    tags: ["Flok", "flok"],
    description: "If you missed Floki - then get on Flok On Solana!",
    notice: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/flok%2FFlok%2Fflok%20logo.jpg33d21191-bebe-4ab5-8185-94c9fc90a12f?alt=media&token=b470d2fa-67ba-49f6-9f27-b0616e39faa6",
    total_supply: null,
    date_launched: 1713075604000,
    approved: false,
    platform: "solana",
    max_supply: null,
    bmc_audit_score: null,
    bmc_audit: false,
    date_added: 1713076372684,
    cmc_id: null,
    quote: null,
  },
  {
    description:
      "At Guild of Guardians, we firmly believe that web3 gaming should instead transform players' invested time and lasting contributions into more meaningful experiences, deeper social bonds, and tangible rewards. We envision a future where the gaming experience takes center stage, where innovation in the in-game economy and digital ownership elevate the industry to new heights.\n\n",
    max_supply: null,
    contract_address: "0x9AB7bb7FdC60f4357ECFef43986818A2A3569c62",
    symbol: "GOG",
    coinName: "Guild of Guardians ",
    bmc_audit: false,
    subreddit: null,
    date_end: 1713111897000,
    date_added: 1713112075261,
    slug: "guild of guardians ",
    id: "guildofguardians357",
    date_launched: 1713111897000,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/GOG%2FGuild%20of%20Guardians%20%2F1.jpgd79e7beb-6cc3-4f9b-9710-2c677c315614?alt=media&token=108b90ce-a834-4a6c-bc72-e0b34bfba610",
    cmc_id: null,
    platform: "ethereum",
    category: null,
    urls: {
      twitter: "https://twitter.com/GuildOfGuardian",
      telegramContact: "https://discord.com/invite/UdejGr9Wg7",
      safu: "",
      kyc: "",
      chart: "https://www.okx.com/trade-spot/gog-usdt",
      source_code: "",
      launchpad: "OKX",
      announcement: "https://www.guildofguardians.com/",
      telegram: "https://discord.com/invite/UdejGr9Wg7",
      launchpadURL: "https://www.okx.com/trade-spot/gog-usdt",
      doxx: "",
      audit: "",
      explorer: "https://www.guildofguardians.com/",
      website: "https://www.guildofguardians.com/",
    },
    approved: false,
    votes: 100,
    tags: ["Guild of Guardians ", "GOG"],
    quote: null,
    notice: null,
    presale: false,
    verified: true,
    total_supply: null,
    infinite_supply: null,
    bmc_audit_score: null,
  },
  {
    bmc_audit: false,
    notice: null,
    cmc_id: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/SWCH%2FSwissCheese%20%2F1.jpgf9322f3b-f6f4-4ab6-81f0-47ce0b04105d?alt=media&token=0215b7fa-7656-47dd-8021-983ed2862745",
    verified: true,
    category: null,
    date_end: 1713112365000,
    symbol: "SWCH",
    max_supply: null,
    quote: null,
    slug: "swisscheese ",
    votes: 100,
    infinite_supply: null,
    description:
      "At Swisscheese, we are at the forefront of this financial transformation, providing a decentralized platform for the secure and efficient trading of tokenized stocks. Users can access fractional ownership of stocks through our platform by using any type of digital token, cryptocurrency, and our native SWCH tokens. Each tokenized stock represents a portion of an underlying stock, allowing users to invest in and trade stocks directly on our decentralized platform. This tokenization process breaks down traditional barriers to entry, enhances market accessibility, and reduces transaction costs for users.\n\n",
    bmc_audit_score: null,
    presale: false,
    urls: {
      launchpadURL: "https://www.mexc.com/exchange/SWCH_USDT",
      safu: "",
      source_code: "",
      announcement: "https://swisscheese.finance/",
      chart: "https://www.mexc.com/exchange/SWCH_USDT",
      launchpad: "MEXC",
      website: "https://swisscheese.finance/",
      explorer: "https://swisscheese.finance/",
      telegramContact: "https://t.me/swisscheesegroup",
      twitter: "https://twitter.com/Swisscheese_fn",
      telegram: "https://t.me/swisscheesegroup",
      kyc: "",
      doxx: "",
      audit: "",
    },
    coinName: "SwissCheese ",
    subreddit: null,
    approved: false,
    id: "swisscheese358",
    contract_address: "0x3ce1327867077b551ae9a6987bf10c9fd08edce1",
    tags: ["SwissCheese ", "SWCH"],
    date_launched: 1713112365000,
    date_added: 1713112458052,
    total_supply: null,
    platform: "polygon",
  },
  {
    date_launched: 1713112718000,
    max_supply: null,
    bmc_audit_score: null,
    id: "apeiron359",
    presale: false,
    infinite_supply: null,
    verified: true,
    slug: "apeiron ",
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/APRS%2FApeiron%20%2F1%2C.jpgb9432192-0b67-4ff9-a67b-5d6d924c7fa6?alt=media&token=a5a07cb1-0667-47fd-81ce-f58cfb36cc87",
    description:
      "Apeiron is a casual competitive mobile game powered by the Ronin Network, rule over planets full of adorable doods, dive into dangerous dungeons, and battle against other players using powerful Avatars. As a newborn god, will you walk the path of good…or evil? Determine the fate of the godiverse in this epic new adventure.\n\n",
    category: null,
    notice: null,
    date_added: 1713112860809,
    approved: false,
    tags: ["Apeiron ", "APRS"],
    bmc_audit: false,
    cmc_id: null,
    coinName: "Apeiron ",
    quote: null,
    votes: 100,
    date_end: 1713112718000,
    contract_address: "0x95b4B8CaD3567B5d7EF7399C2aE1d7070692aB0D",
    platform: "eth",
    urls: {
      launchpad: "BYBIT",
      doxx: "",
      website: "https://apeironnft.com/",
      twitter: "https://twitter.com/ApeironNFT",
      audit: "",
      telegramContact: "https://discord.com/invite/apeiron-doodaria",
      kyc: "",
      source_code: "",
      chart: "https://www.bybit.com/en/trade/spot/APRS/USDT",
      safu: "",
      announcement: "https://apeironnft.com/",
      telegram: "https://discord.com/invite/apeiron-doodaria",
      explorer: "https://apeironnft.com/",
      launchpadURL: "https://www.bybit.com/en/trade/spot/APRS/USDT",
    },
    subreddit: null,
    symbol: "APRS",
    total_supply: null,
  },
  {
    quote: null,
    category: null,
    contract_address: "0x8fc17671D853341D9e8B001F5Fc3C892d09CB53A",
    date_end: 1712872962000,
    symbol: "BLOCK",
    votes: 100,
    subreddit: null,
    max_supply: null,
    infinite_supply: null,
    date_added: 1712873083658,
    slug: "blockgames ",
    cmc_id: null,
    bmc_audit_score: null,
    approved: true,
    bmc_audit: false,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/BLOCK%2FBlockGames%20%2F1.jpge5438390-52a1-4079-aab9-39cc19c2548e?alt=media&token=708e5306-7add-4543-99d4-7d44aa7a1d2c",
    description:
      "BlockGames is introducing a new era of rewarded data ownership for mobile gamers and publishers worldwide. By creating an extensive, interconnected Player Network, it powers the next wave of groundbreaking publishing applications and gaming experiences driven by rewards within real data economies.\n\n",
    coinName: "BlockGames ",
    id: "blockgames322",
    tags: ["BlockGames ", "BLOCK"],
    notice: null,
    total_supply: null,
    presale: false,
    date_launched: 1712872962000,
    verified: true,
    urls: {
      doxx: "",
      chart: "https://www.kucoin.com/trade/BLOCK-USDT?rcode=rPH7VCS",
      kyc: "",
      safu: "",
      announcement: "https://www.blockgames.com/",
      twitter: "https://twitter.com/getblockgames",
      source_code: "",
      telegram: "https://discord.gg/blockgames",
      launchpadURL: "https://www.kucoin.com/trade/BLOCK-USDT?rcode=rPH7VCS",
      audit: "",
      telegramContact: "https://discord.gg/blockgames",
      launchpad: "Kucoin",
      website: "https://www.blockgames.com/",
      explorer: "https://www.blockgames.com/",
    },
    platform: "ethereum",
  },
  {
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/CHKN%2FChickencoin%20%2F1.jpge1b49124-1c0e-4b03-9fe2-d0456b9d9f68?alt=media&token=12ab8d8f-f437-44e9-bca5-e3578df9a101",
    quote: null,
    contract_address: "0xD55210Bb6898C021a19de1F58d27b71f095921Ee",
    date_launched: 1713113439000,
    notice: null,
    total_supply: null,
    description:
      "Chickencoin is a ERC-20 memecoin forked from Pepecoin for the web3 community. CHKN distribution includes an airdrop of 20% to the PEPE community holders, 70% through a fair launch on Uniswap v2, a 6.9% dev allocation under multi-sig, and 3.1% for community marketing. Follow our Twitter to watch the Chickencoin mascot, Silo, throughout his memecoin journey.\n",
    bmc_audit: false,
    symbol: "CHKN",
    platform: "ethereum",
    cmc_id: null,
    tags: ["Chickencoin ", "CHKN"],
    subreddit: null,
    verified: true,
    date_added: 1713113555515,
    votes: 100,
    bmc_audit_score: null,
    urls: {
      audit: "",
      doxx: "",
      launchpad: "MEXC",
      launchpadURL: "https://www.mexc.com/exchange/CHKN_USDT",
      announcement: "https://www.chickencoin.com/",
      chart: "https://www.mexc.com/exchange/CHKN_USDT",
      twitter: "https://twitter.com/chickencoin_eth",
      explorer: "https://www.chickencoin.com/",
      website: "https://www.chickencoin.com/",
      telegram: "https://t.me/chickencoin_eth",
      source_code: "",
      telegramContact: "https://t.me/chickencoin_eth",
      kyc: "",
      safu: "",
    },
    category: null,
    infinite_supply: null,
    date_end: 1713113439000,
    approved: true,
    slug: "chickencoin ",
    coinName: "Chickencoin ",
    id: "chickencoin360",
    presale: false,
    max_supply: null,
  },
  {
    id: "parcl373",
    max_supply: null,
    votes: 100,
    urls: {
      explorer: "https://www.parcl.co/",
      telegram: "https://discord.com/invite/parcl",
      audit: "",
      source_code: "",
      announcement: "https://www.parcl.co/",
      launchpad: "Gateio",
      kyc: "",
      doxx: "",
      twitter: "https://twitter.com/parcl",
      telegramContact: "https://discord.com/invite/parcl",
      chart: "https://www.gate.io/trade/PRCL_USDT",
      launchpadURL: "https://www.gate.io/trade/PRCL_USDT",
      safu: "",
      website: "https://www.parcl.co/",
    },
    contract_address: "4LLbsb5ReP3yEtYzmXewyGjcir5uXtKFURtaEUVC2AHs",
    quote: null,
    tags: ["Parcl ", "PRCL"],
    approved: true,
    slug: "parcl ",
    symbol: "PRCL",
    date_end: 1713274161000,
    subreddit: null,
    coinName: "Parcl ",
    description:
      "The Parcl Ecosystem, which includes Parcl, Parcl Labs, and Parcl Limited, develops and governs the Parcl Protocol, a decentralized exchange that allows users to get long or short exposure to real-world real estate prices via a decentralized exchange.\n\n",
    bmc_audit: false,
    category: null,
    verified: true,
    presale: false,
    cmc_id: null,
    date_launched: 1713274161000,
    total_supply: null,
    notice: null,
    platform: "solana",
    bmc_audit_score: null,
    date_added: 1713274398777,
    infinite_supply: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/PRCL%2FParcl%20%2FmUIvDnYk_400x400.jpgb0db0343-e0ab-46c1-b510-ec055d1f8382?alt=media&token=57fc3a96-67c8-4ac8-adf7-510527dd2c87",
  },
  {
    date_end: 1713275570000,
    category: null,
    bmc_audit_score: null,
    description:
      "Arcade is the multi-chain GameFi platform that gives token holders the opportunity to earn meaningful rewards, from various Play-2-Earn games, without direct gameplay or asset ownership. Arcade, or our NFT Collector network, owns the assets and through the strategic infrastructure of guilds, players and game developers, in-game earnings are passed along via our revolutionary Mission Pools concept.\n\n",
    bmc_audit: false,
    infinite_supply: null,
    notice: null,
    date_added: 1713275741246,
    date_launched: 1713275570000,
    total_supply: null,
    cmc_id: null,
    verified: true,
    slug: "arcade",
    votes: 100,
    quote: null,
    urls: {
      safu: "",
      website: "https://www.arcade2earn.io/",
      twitter: "https://twitter.com/arcade2earn",
      chart: "https://www.kucoin.com/trade/ARC-USDT?rcode=rPH7VCS",
      telegramContact: "https://t.me/arcade2earn",
      source_code: "",
      launchpad: "Kucoin ",
      kyc: "",
      launchpadURL: "https://www.kucoin.com/trade/ARC-USDT?rcode=rPH7VCS",
      explorer: "https://www.arcade2earn.io/",
      doxx: "",
      announcement: "https://www.arcade2earn.io/",
      telegram: "https://t.me/arcade2earn",
      audit: "",
    },
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/ARC%2FArcade%2F1111.jpgc5914ef8-13a6-40ac-b327-2e2b14b61b44?alt=media&token=9b628550-0012-452d-85a2-5ff930b87a67",
    platform: "ethereum",
    max_supply: null,
    symbol: "ARC",
    approved: true,
    tags: ["Arcade", "ARC"],
    coinName: "Arcade",
    contract_address: "0x2903Bd7dB50f300b0884f7a15904bAffc77f3eC7",
    subreddit: null,
    presale: false,
    id: "arcade374",
  },
  {
    category: null,
    bmc_audit_score: null,
    presale: false,
    bmc_audit: false,
    max_supply: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/KARCON%2FKAARIGAR%20Connect%2F1.jpg6fb72fb7-3f54-4dab-82e7-4d5fef0ce6f0?alt=media&token=0091638b-4f9a-40df-adb8-1140505fccd4",
    votes: 100,
    tags: ["KAARIGAR Connect", "KARCON"],
    infinite_supply: null,
    symbol: "KARCON",
    verified: true,
    total_supply: null,
    description:
      "Where skilled professionals find their perfect match\nthrough AI. Effortlessly expand your possibilities with\nWeb3.",
    id: "kaarigarconnect381",
    approved: true,
    date_end: 1713308562000,
    contract_address: "0x44AF2390d7ed22966D3E570BFfB648817E4335f0",
    slug: "kaarigar connect",
    date_launched: 1713308562000,
    coinName: "KAARIGAR Connect",
    platform: "ethereum",
    date_added: 1713308803100,
    quote: null,
    urls: {
      doxx: "",
      safu: "",
      twitter: "https://twitter.com/KC_Web3",
      explorer: "https://www.kaarigarconnect.xyz/",
      source_code: "",
      launchpadURL: "https://www.mexc.com/exchange/KARCON_USDT",
      launchpad: "MEXC",
      telegram: "https://t.me/kaarigarconnect",
      website: "https://www.kaarigarconnect.xyz/",
      audit: "",
      kyc: "",
      chart: "https://www.mexc.com/exchange/KARCON_USDT",
      telegramContact: "https://t.me/kaarigarconnect",
      announcement: "https://www.kaarigarconnect.xyz/",
    },
    subreddit: null,
    notice: null,
    cmc_id: null,
  },
  {
    notice: null,
    id: "avalox386",
    approved: true,
    bmc_audit_score: null,
    presale: false,
    infinite_supply: null,
    total_supply: null,
    quote: null,
    contract_address: "0x1209810df5370f68b28e6832dc4ac80072e2d0b8",
    verified: true,
    subreddit: null,
    cmc_id: null,
    category: null,
    description:
      "Introducing Avalox, the ultimate blend of Meme and DeFi on the Avalanche chain! Embrace the power of laughter and financial innovation as Avalox brings joy to the crypto space. Token holders enjoy meme-worthy moments while benefiting from decentralized finance opportunities. Join the community, ride the waves of humor and financial growth with Avalox!\n\n\n\n\n",
    max_supply: null,
    votes: "1698",
    bmc_audit: "true",
    tags: ["AVALOX ", "AVALOX"],
    date_added: 1713378149222,
    platform: "avalanche",
    symbol: "AVALOX",
    date_launched: 1713377866000,
    urls: {
      youtube: null,
      instagram: null,
      launchpadURL: "https://www.mexc.com/exchange/AVALOX_USDT",
      doxx: null,
      safu: null,
      twitter: "https://twitter.com/AVALOX_AVAX",
      reddit: null,
      source_code: null,
      audit: null,
      announcement: "https://avaloxtoken.com/",
      telegramContact: "https://t.me/Avalox_avax",
      kyc: null,
      website: "https://avaloxtoken.com/",
      facebook: null,
      launchpad: "MEXC",
      technical_doc: null,
      chart: "https://www.mexc.com/exchange/AVALOX_USDT",
      telegram: "https://t.me/Avalox_avax",
      explorer: "https://avaloxtoken.com/",
    },
    slug: "avalox ",
    date_end: 1713377866000,
    coinName: "AVALOX ",
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/AVALOX%2FAVALOX%20%2F1.jpg650b3707-7ef1-4977-90ed-052b6ddb5073?alt=media&token=cad7a950-222d-4735-bdc5-eefbcc5c6744",
  },
  {
    id: "multiuniversecentral392",
    date_launched: 1713513882000,
    date_added: 1713514050175,
    cmc_id: null,
    category: null,
    bmc_audit: "true",
    subreddit: null,
    description:
      "Multi Universe Central (MUC) is a project to build an infinite universe and an ecosystem that supports it, focusing on Original PFP projects and GameFi Alliances.\n",
    votes: "1634",
    slug: "multi universe central",
    urls: {
      safu: null,
      technical_doc: null,
      launchpadURL: "https://www.gate.io/trade/MUC_USDT",
      website: "https://multiuniversecentral.io/",
      twitter: "https://twitter.com/muc_io",
      telegramContact: "https://t.me/MUC_ann",
      reddit: null,
      launchpad: "Gateio",
      facebook: null,
      doxx: null,
      audit: null,
      announcement: "https://multiuniversecentral.io/",
      instagram: null,
      source_code: null,
      chart: "https://www.gate.io/trade/MUC_USDT",
      kyc: null,
      explorer: "https://multiuniversecentral.io/",
      youtube: null,
      telegram: "https://t.me/MUC_ann",
    },
    tags: ["Multi Universe Central", "MUC"],
    symbol: "MUC",
    quote: null,
    verified: true,
    platform: "polygon",
    total_supply: null,
    approved: true,
    date_end: 1713513882000,
    notice: null,
    infinite_supply: null,
    coinName: "Multi Universe Central",
    bmc_audit_score: null,
    contract_address: "0x03b92ebf0615d44d8c782c209e4405b74cb77d1d",
    max_supply: null,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/MUC%2FMulti%20Universe%20Central%2F10.jpg5bb9bb47-7388-424c-a153-311700350437?alt=media&token=32419151-5741-463b-91e9-10dc09120ac0",
    presale: false,
  },
  {
    notice: null,
    infinite_supply: null,
    bmc_audit: "true",
    category: null,
    presale: false,
    verified: true,
    date_launched: 1713515864000,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/MERL%2FMerlin%20Chain%20%2F1111.jpg0732ea77-701a-450e-9b5c-2a3337c47623?alt=media&token=4864c012-c63c-43ad-975d-65c73caab570",
    urls: {
      launchpad: "Gateio",
      telegramContact: "https://t.me/merlin_chain",
      reddit: null,
      facebook: null,
      source_code: null,
      doxx: null,
      instagram: null,
      kyc: null,
      chart: "https://www.gate.io/trade/MUC_USDT",
      youtube: null,
      safu: null,
      launchpadURL: "https://www.gate.io/trade/MUC_USDT",
      announcement: "https://merlinchain.io/",
      audit: null,
      explorer: "https://merlinchain.io/",
      telegram: "https://t.me/merlin_chain",
      website: "https://merlinchain.io/",
      twitter: "https://twitter.com/MerlinLayer2",
      technical_doc: null,
    },
    tags: ["Merlin Chain ", "MERL"],
    symbol: "MERL",
    votes: "1523",
    date_added: 1713516098028,
    cmc_id: null,
    total_supply: null,
    subreddit: null,
    max_supply: null,
    id: "merlinchain393",
    platform: "tba",
    description:
      " Merlin Chain serves as a Layer 2 solution for Bitcoin, incorporating essential components like ZK-Rollup networks, decentralized oracle networks, and fraud proofs within the Bitcoin chain. Its primary objective is to empower the native assets, protocols, and application ecosystem of Bitcoin Layer 1, facilitating ongoing innovation and maximizing asset potential on Layer 2 networks. MERL is the native token of Merlin Chain which is used for: Staking: Staking $MERL contributes to the overall security of Merlin Chain.",
    bmc_audit_score: null,
    approved: false,
    quote: null,
    coinName: "Merlin Chain ",
    slug: "merlin chain ",
    date_end: 1713515864000,
    contract_address: "0x5c46bFF4B38dc1EAE09C5BAc65872a1D8bc87378",
  },
  {
    slug: "cats of sol ",
    contract_address: "3obNTknsf4hq5pNh3GDPEhyCB9WTKJJzM2PcqfKgLmBu",
    quote: null,
    description:
      "Meme token collides with world of NFTs. Cats of Sol are storming the crypto scene! These aren’t your average alley cats; they’re the kings of Sol City, bringing swagger and street smarts to the blockchain.\n\n\n\n",
    date_launched: 1712788310000,
    total_supply: null,
    max_supply: null,
    urls: {
      launchpad: "MEXC",
      technical_doc: null,
      reddit: null,
      chart: "https://www.mexc.com/exchange/COS_USDT",
      telegram: "https://t.me/catsofsolana",
      announcement: "http://www.catsofsol.com/",
      instagram: null,
      safu: null,
      kyc: null,
      doxx: null,
      twitter: "https://twitter.com/catsofsol",
      facebook: null,
      youtube: null,
      source_code: null,
      website: "http://www.catsofsol.com/",
      audit: null,
      launchpadURL: "https://www.mexc.com/exchange/COS_USDT",
      explorer: "http://www.catsofsol.com/",
      telegramContact: "https://t.me/catsofsolana",
    },
    platform: "solana",
    bmc_audit_score: null,
    id: "catsofsol307",
    notice: null,
    presale: false,
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/COS%2FCats%20Of%20Sol%20%2F1.jpg824e8b0a-74b2-4f59-a4d1-3e80821268b7?alt=media&token=ea1ea7c2-4655-4c46-9e71-73db2a7329ec",
    bmc_audit: "true",
    cmc_id: "4",
    tags: ["Cats Of Sol ", "COS"],
    date_end: 1712788310000,
    category: null,
    date_added: 1712788472163,
    subreddit: null,
    symbol: "COS",
    votes: "2345",
    approved: true,
    coinName: "Cats Of Sol ",
    verified: true,
    infinite_supply: null,
  },
  {
    id: "vitainu401",
    logo: "https://firebasestorage.googleapis.com/v0/b/bmc-database-f73bd.appspot.com/o/VINU%2FVITA%20INU%2F11.jpgbd619dfa-262a-4d5d-9bc8-e709c9f28b56?alt=media&token=0a2b4f25-07ed-41cc-9293-ddb1be0411be",
    verified: true,
    cmc_id: null,
    presale: false,
    subreddit: null,
    quote: null,
    platform: "base",
    max_supply: null,
    category: null,
    total_supply: null,
    date_end: 1713561527000,
    tags: ["VITA INU", "VINU"],
    notice: null,
    contract_address: "0x72cCF64EE5E2C7629eE4eEe3e6AD6990289178ae",
    symbol: "VINU",
    coinName: "VITA INU",
    description:
      "The only memecoin with real world utility. Zero fees, instant settlement and the highest energy efficiency out there. What more could you ask for? Join our fast growing community!\n\n",
    date_added: 1713562129717,
    votes: 100,
    slug: "vita inu",
    approved: true,
    infinite_supply: null,
    date_launched: 1713561527000,
    bmc_audit_score: null,
    urls: {
      chart: "https://www.kucoin.com/trade/VINU-USDT",
      safu: "",
      doxx: "",
      telegramContact: "https://t.me/vitainu",
      twitter: "https://twitter.com/VitaInuCoin",
      explorer: "https://vitainu.org/",
      source_code: "",
      launchpadURL: "https://www.kucoin.com/trade/VINU-USDT",
      announcement: "https://vitainu.org/",
      launchpad: "Kucoin",
      kyc: "",
      audit: "",
      website: "https://vitainu.org/",
      telegram: "https://t.me/vitainu",
    },
    bmc_audit: false,
  },
];




