{/* <div>
  <div className="stats shadow">
    <div className="stat">
      <div className="stat-title">Total Page Views</div>
      <div className="stat-value">89,400</div>
      <div className="stat-desc">21% more than last month</div>
    </div>
  </div>

  <div className="overflow-x-auto">
    {coins.map((coin, index) => (
      <>
        <div className="my-4 flex flex-row">
          <img src={coin.logoURL} className="w-12 h-12 rounded-xl" />

          <span className="my-auto text-sm ml-5">
            {coin.coinName}
            <br />
            {coin.symbol}
          </span>

          <span></span>
        </div>
      </>
    ))}
  </div>
</div>; */}

export const data = [
  {
    verified: false,
    symbol: "Coin Symbol",
    safuURL: "SAFU URL",
    contractAddress: "Contract Address",
    chain: "avalanche",
    redditURL: "Reddit URL",
    websiteURL: "Website URL",
    twitterURL: "Twitter URL",
    votes: 0,
    telegramContact: "Telegram for Contact",
    doxxURL: "Doxx URL",
    telegramURL: "Telegram URL",
    kycURL: "KYC URL",
    auditURL: "Audit URL",
    instagramURL: "Instagram URL",
    discordURL: "Discord URL",
    promoted: false,
    facebookURL: "Facebook URL",
    presale: false,
    youtubeURL: "Youtube URL",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg11b586d0-70e9-48fb-8b1b-b1c7f788d173?alt=media&token=769d13c6-177d-41f0-973a-d0c52187afa4",
    email: "smartjeremy01@gmail.com",
    coinName: "Coin Name",
    description: "Coin Description",
    id: "4duwgOYB2psAAM2m7GkA",
  },
  {
    coinName: "Contract Address",
    kycURL: "",
    auditURL: "",
    instagramURL: "",
    twitterURL: "",
    verified: false,
    presale: true,
    telegramURL: "Contract Address",
    email: "smartjeremy01@gmail.com",
    facebookURL: "",
    redditURL: "",
    youtubeURL: "",
    discordURL: "",
    votes: 0,
    promoted: false,
    symbol: "Contract Address",
    websiteURL: "",
    contractAddress: "Contract Address",
    chain: "bsc",
    description: "Contract Address",
    safuURL: "",
    doxxURL: "",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FContract%20Address%2F117041814.jpeg45b7216a-92d2-4bb1-8c1f-d4a67a34dc98?alt=media&token=ef3b99c6-5fde-4655-99fb-85284d4d0d37",
    telegramContact: "Contract Address",
    id: "4jaUSYtg5m1JQvQ8siBV",
  },
  {
    contractAddress: "Contract Address",
    email: "smartjeremy01@gmail.com",
    instagramURL: "Instagram URL",
    safuURL: "SAFU URL",
    promoted: false,
    symbol: "Coin Symbol",
    auditURL: "Audit URL",
    votes: 0,
    twitterURL: "Twitter URL",
    telegramURL: "Telegram URL",
    telegramContact: "Telegram for Contact",
    presale: false,
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpegc4a51eb3-7b8f-4ff2-a220-8ff838b46021?alt=media&token=605914c1-feaa-4427-8de7-2fda790c0fd5",
    chain: "avalanche",
    description: "Coin Description",
    youtubeURL: "Youtube URL",
    coinName: "Coin Name",
    doxxURL: "Doxx URL",
    kycURL: "KYC URL",
    websiteURL: "Website URL",
    redditURL: "Reddit URL",
    discordURL: "Discord URL",
    facebookURL: "Facebook URL",
    verified: false,
    id: "4wZTG8Q6niJjpatsUCcn",
  },
  {
    doxxURL: "Doxx URL",
    websiteURL: "Website URL",
    safuURL: "SAFU URL",
    facebookURL: "Facebook URL",
    promoted: false,
    redditURL: "Reddit URL",
    description: "Coin Description",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpegcac634dd-cee7-443c-9854-2913b1c2c4ec?alt=media&token=6e1bacfe-a1b7-4000-8915-7369121adfab",
    presale: false,
    instagramURL: "Instagram URL",
    coinName: "Coin Name",
    email: "smartjeremy01@gmail.com",
    telegramURL: "Telegram URL",
    symbol: "Coin Symbol",
    verified: false,
    votes: 0,
    kycURL: "KYC URL",
    chain: "avalanche",
    discordURL: "Discord URL",
    youtubeURL: "Youtube URL",
    telegramContact: "Telegram for Contact",
    auditURL: "Audit URL",
    contractAddress: "Contract Address",
    twitterURL: "Twitter URL",
    id: "6bOfY8u956Cii6i4LlsT",
  },
  {
    symbol: "Contract Address",
    auditURL: "",
    discordURL: "",
    chain: "bsc",
    telegramContact: "Contract Address",
    votes: 0,
    promoted: false,
    telegramURL: "Contract Address",
    email: "smartjeremy01@gmail.com",
    description: "Contract Address",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FContract%20Address%2F117041814.jpeg37c69d17-989e-49f8-af66-e98d16111c89?alt=media&token=0f1640f7-1ba2-40ac-b1e1-fa157281ade3",
    facebookURL: "",
    doxxURL: "",
    safuURL: "",
    youtubeURL: "",
    kycURL: "",
    presale: true,
    contractAddress: "Contract Address",
    verified: false,
    websiteURL: "",
    coinName: "Contract Address",
    twitterURL: "",
    redditURL: "",
    instagramURL: "",
    id: "9QI1KMzEHKQitY7y1n9d",
  },
  {
    chain: "avalanche",
    contractAddress: "Contract Address",
    presale: true,
    promoted: false,
    votes: 0,
    twitterURL: "Twitter URL",
    youtubeURL: "Youtube URL",
    telegramURL: "Telegram URL",
    telegramContact: "Telegram for Contact",
    safuURL: "SAFU URL",
    verified: false,
    kycURL: "KYC URL",
    auditURL: "Audit URL",
    instagramURL: "Instagram URL",
    symbol: "Coin Symbol",
    coinName: "Coin Name",
    description: "Coin Description",
    doxxURL: "Doxx URL",
    redditURL: "Reddit URL",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg8c55dfe7-38e0-4fe5-80ac-60dee7852f74?alt=media&token=8450751c-d84f-41c8-a615-c2e9e28b2da4",
    websiteURL: "Website URL",
    discordURL: "Discord URL",
    facebookURL: "Facebook URL",
    email: "smartjeremy01@gmail.com",
    id: "C00NwWDlQCRl1zfw9qxf",
  },
  {
    chain: "avalanche",
    email: "smartjeremy01@gmail.com",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg10b2a300-06b3-46b4-b49c-7b6d82e257bb?alt=media&token=6038c703-7571-45d5-8e13-5bf81cbb2458",
    discordURL: "Discord URL",
    description: "Coin Description",
    presale: false,
    promoted: false,
    symbol: "Coin Symbol",
    redditURL: "Reddit URL",
    votes: 0,
    doxxURL: "Doxx URL",
    telegramURL: "Telegram URL",
    coinName: "Coin Name",
    auditURL: "Audit URL",
    verified: false,
    instagramURL: "Instagram URL",
    telegramContact: "Telegram for Contact",
    twitterURL: "Twitter URL",
    safuURL: "SAFU URL",
    websiteURL: "Website URL",
    contractAddress: "Contract Address",
    kycURL: "KYC URL",
    youtubeURL: "Youtube URL",
    facebookURL: "Facebook URL",
    id: "CMjeZmhXuqEQdDnVv91O",
  },
  {
    websiteURL: "Website URL",
    twitterURL: "Twitter URL",
    doxxURL: "Doxx URL",
    chain: "avalanche",
    symbol: "Coin Symbol",
    telegramContact: "Telegram for Contact",
    coinName: "Coin Name",
    kycURL: "KYC URL",
    redditURL: "Reddit URL",
    youtubeURL: "Youtube URL",
    telegramURL: "Telegram URL",
    safuURL: "SAFU URL",
    verified: false,
    contractAddress: "Contract Address",
    instagramURL: "Instagram URL",
    discordURL: "Discord URL",
    presale: false,
    votes: 0,
    description: "Coin Description",
    email: "smartjeremy01@gmail.com",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpegfa4c30cb-03c2-4bda-976c-742c53d161b8?alt=media&token=b1dadf04-dcaa-47c0-a2de-d779fea6c868",
    promoted: false,
    facebookURL: "Facebook URL",
    auditURL: "Audit URL",
    id: "ESTj7eK2U6cr0SkYHQOo",
  },
  {
    telegramContact: "Telegram for Contact",
    votes: 0,
    auditURL: "Audit URL",
    chain: "avalanche",
    facebookURL: "Facebook URL",
    verified: false,
    email: "smartjeremy01@gmail.com",
    websiteURL: "Website URL",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg388a98c6-60ca-43e3-8896-f73dbd1d9125?alt=media&token=1fa0ce14-88ed-459f-b855-dfa66378d5e3",
    coinName: "Coin Name",
    safuURL: "SAFU URL",
    telegramURL: "Telegram URL",
    contractAddress: "Contract Address",
    description: "Coin Description",
    instagramURL: "Instagram URL",
    redditURL: "Reddit URL",
    promoted: false,
    twitterURL: "Twitter URL",
    kycURL: "KYC URL",
    discordURL: "Discord URL",
    youtubeURL: "Youtube URL",
    symbol: "Coin Symbol",
    presale: false,
    doxxURL: "Doxx URL",
    id: "EgQYYCzCn5hriYs5hIi6",
  },
  {
    chain: "bsc",
    facebookURL: "",
    symbol: "Contract Address",
    discordURL: "",
    auditURL: "",
    redditURL: "",
    description: "Contract Address",
    contractAddress: "Contract Address",
    promoted: false,
    instagramURL: "",
    safuURL: "",
    email: "smartjeremy01@gmail.com",
    verified: false,
    presale: true,
    telegramContact: "Contract Address",
    websiteURL: "",
    telegramURL: "Contract Address",
    youtubeURL: "",
    doxxURL: "",
    twitterURL: "",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FContract%20Address%2F117041814.jpegbd7d1385-9e05-4242-a370-29063a351567?alt=media&token=d9017e19-5089-4fad-86f1-c34328c1fe27",
    votes: 0,
    coinName: "Contract Address",
    kycURL: "",
    id: "KFBNffNelG0UukA24JFW",
  },
  {
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2Fbright-abstract-background-orange-color-free-vector.jpegb6b9d770-f3cd-4b2d-ad19-b4a8b6263ddf?alt=media&token=34673dde-5413-4e4f-8a2f-e37924849087",
    chain: "avalanche",
    description: "Coin Description",
    safuURL: "SAFU URL",
    twitterURL: "Twitter URL",
    doxxURL: "Doxx URL",
    instagramURL: "Instagram URL",
    contractAddress: "Contract Address",
    email: "smartjeremy01@gmail.com",
    promoted: false,
    coinName: "Coin Name",
    verified: false,
    redditURL: "Reddit URL",
    youtubeURL: "Youtube URL",
    auditURL: "Audit URL",
    presale: false,
    discordURL: "Discord URL",
    facebookURL: "Facebook URL",
    symbol: "Coin Symbol",
    websiteURL: "Website URL",
    votes: 0,
    kycURL: "KYC URL",
    telegramContact: "Telegram for Contact",
    telegramURL: "Telegram URL",
    id: "Ktm460KcYN4cjzqbpD8t",
  },
  {
    discordURL: "Discord URL",
    instagramURL: "Instagram URL",
    youtubeURL: "Youtube URL",
    doxxURL: "Doxx URL",
    twitterURL: "Twitter URL",
    description: "Coin Description",
    votes: 0,
    telegramContact: "Telegram for Contact",
    promoted: false,
    redditURL: "Reddit URL",
    safuURL: "SAFU URL",
    email: "smartjeremy01@gmail.com",
    chain: "avalanche",
    telegramURL: "Telegram URL",
    coinName: "Coin Name",
    auditURL: "Audit URL",
    verified: false,
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg1900b444-3482-46f1-810c-cc86613ff149?alt=media&token=886905fd-8d7f-4a7b-be1e-525654af0724",
    facebookURL: "Facebook URL",
    websiteURL: "Website URL",
    symbol: "Coin Symbol",
    contractAddress: "Contract Address",
    presale: true,
    kycURL: "KYC URL",
    id: "OnGkIHNzWtWz7MGW8ca4",
  },
  {
    facebookURL: "Facebook URL",
    discordURL: "Discord URL",
    websiteURL: "Website URL",
    chain: "avalanche",
    promoted: false,
    presale: true,
    twitterURL: "Twitter URL",
    telegramURL: "Telegram URL",
    safuURL: "SAFU URL",
    youtubeURL: "Youtube URL",
    auditURL: "Audit URL",
    instagramURL: "Instagram URL",
    redditURL: "Reddit URL",
    coinName: "Coin Name",
    verified: false,
    kycURL: "KYC URL",
    symbol: "Coin Symbol",
    contractAddress: "Contract Address",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2Fbright-abstract-background-orange-color-free-vector.jpegf1e38053-f9a4-49d0-964e-47c11af470ba?alt=media&token=4bcf673e-5f41-4cf6-9b96-36aae859acb7",
    doxxURL: "Doxx URL",
    email: "smartjeremy01@gmail.com",
    description: "Coin Description",
    telegramContact: "Telegram for Contact",
    votes: 0,
    id: "RG4xCm71bLZyxcpdxDgg",
  },
  {
    facebookURL: "Facebook URL",
    doxxURL: "Doxx URL",
    votes: 0,
    safuURL: "SAFU URL",
    instagramURL: "Instagram URL",
    presale: true,
    redditURL: "Reddit URL",
    promoted: false,
    verified: false,
    discordURL: "Discord URL",
    description: "Coin Description",
    auditURL: "Audit URL",
    chain: "avalanche",
    symbol: "Coin Symbol",
    contractAddress: "Contract Address",
    twitterURL: "Twitter URL",
    kycURL: "KYC URL",
    telegramURL: "Telegram URL",
    youtubeURL: "Youtube URL",
    telegramContact: "Telegram for Contact",
    websiteURL: "Website URL",
    email: "smartjeremy01@gmail.com",
    coinName: "Coin Name",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpegd6f3cf7d-6033-4673-8636-86a10da7ddae?alt=media&token=3f013d1d-8667-4aa9-9dda-c53fb6992ca7",
    id: "RMbhKRxNjAE8HxGElDhc",
  },
  {
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2Fbright-abstract-background-orange-color-free-vector.jpeg84dcdf28-b642-40f1-877f-1a3eb411e1f9?alt=media&token=620248fa-80a2-4af5-9aa1-4212c3192967",
    auditURL: "Audit URL",
    facebookURL: "Facebook URL",
    chain: "avalanche",
    websiteURL: "Website URL",
    doxxURL: "Doxx URL",
    safuURL: "SAFU URL",
    votes: 0,
    presale: true,
    symbol: "Coin Symbol",
    telegramURL: "Telegram URL",
    contractAddress: "Contract Address",
    coinName: "Coin Name",
    verified: false,
    instagramURL: "Instagram URL",
    twitterURL: "Twitter URL",
    email: "smartjeremy01@gmail.com",
    description: "Coin Description",
    youtubeURL: "Youtube URL",
    promoted: false,
    telegramContact: "Telegram for Contact",
    kycURL: "KYC URL",
    redditURL: "Reddit URL",
    discordURL: "Discord URL",
    id: "RPC7KGtOWQDVC9wCTXgb",
  },
  {
    votes: 0,
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpegebbca821-039b-4666-9337-3a48f52e737b?alt=media&token=44c0e870-9a7f-4303-924f-036357ba3a2d",
    description: "Coin Description",
    redditURL: "Reddit URL",
    chain: "avalanche",
    auditURL: "Audit URL",
    presale: true,
    doxxURL: "Doxx URL",
    verified: false,
    promoted: false,
    kycURL: "KYC URL",
    telegramContact: "Telegram for Contact",
    discordURL: "Discord URL",
    telegramURL: "Telegram URL",
    safuURL: "SAFU URL",
    facebookURL: "Facebook URL",
    twitterURL: "Twitter URL",
    youtubeURL: "Youtube URL",
    symbol: "Coin Symbol",
    contractAddress: "Contract Address",
    websiteURL: "Website URL",
    instagramURL: "Instagram URL",
    email: "smartjeremy01@gmail.com",
    coinName: "Coin Name",
    id: "WqaH86UrQxRfdVTysffe",
  },
  {
    symbol: "Coin Symbol",
    chain: "avalanche",
    presale: false,
    telegramContact: "Telegram for Contact",
    description: "Coin Description",
    youtubeURL: "Youtube URL",
    kycURL: "KYC URL",
    verified: false,
    safuURL: "SAFU URL",
    contractAddress: "Contract Address",
    twitterURL: "Twitter URL",
    email: "smartjeremy01@gmail.com",
    websiteURL: "Website URL",
    discordURL: "Discord URL",
    redditURL: "Reddit URL",
    telegramURL: "Telegram URL",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg12ea46fc-295d-4c72-9839-cdf28ed952b3?alt=media&token=ec2095d7-f227-4e46-abbf-25e77ed756a1",
    facebookURL: "Facebook URL",
    doxxURL: "Doxx URL",
    votes: 0,
    auditURL: "Audit URL",
    promoted: false,
    instagramURL: "Instagram URL",
    coinName: "Coin Name",
    id: "eA4sefZKPBx8iiMs6pkP",
  },
  {
    youtubeURL: "Youtube URL",
    discordURL: "Discord URL",
    websiteURL: "Website URL",
    promoted: false,
    telegramURL: "Telegram URL",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2Fbright-abstract-background-orange-color-free-vector.jpegc17c3e3e-c768-4654-8335-43fdfdd0465d?alt=media&token=349d3805-a50b-4d4c-8ba6-744efdf17b24",
    doxxURL: "Doxx URL",
    presale: false,
    kycURL: "KYC URL",
    contractAddress: "Contract Address",
    telegramContact: "Telegram for Contact",
    facebookURL: "Facebook URL",
    redditURL: "Reddit URL",
    symbol: "Coin Symbol",
    chain: "avalanche",
    description: "Coin Description",
    twitterURL: "Twitter URL",
    auditURL: "Audit URL",
    votes: 0,
    instagramURL: "Instagram URL",
    verified: false,
    email: "smartjeremy01@gmail.com",
    coinName: "Coin Name",
    safuURL: "SAFU URL",
    id: "icGCrUf4FhcnUFzPAybC",
  },
  {
    symbol: "Coin Symbol",
    youtubeURL: "Youtube URL",
    description: "Coin Description",
    instagramURL: "Instagram URL",
    telegramContact: "Telegram for Contact",
    contractAddress: "Contract Address",
    redditURL: "Reddit URL",
    presale: false,
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg2ced6de8-d10f-4cd9-838e-cb0a75c7e13b?alt=media&token=d208ed4b-6c1a-42d8-9be5-c44c393b5e38",
    discordURL: "Discord URL",
    chain: "avalanche",
    auditURL: "Audit URL",
    telegramURL: "Telegram URL",
    promoted: false,
    email: "smartjeremy01@gmail.com",
    websiteURL: "Website URL",
    verified: false,
    twitterURL: "Twitter URL",
    facebookURL: "Facebook URL",
    kycURL: "KYC URL",
    votes: 0,
    doxxURL: "Doxx URL",
    safuURL: "SAFU URL",
    coinName: "Coin Name",
    id: "qrNecL6uYKngdwRUmfq7",
  },
  {
    safuURL: "SAFU URL",
    presale: true,
    contractAddress: "Contract Address",
    redditURL: "Reddit URL",
    email: "smartjeremy01@gmail.com",
    kycURL: "KYC URL",
    websiteURL: "Website URL",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeg288f262c-57bb-4742-bc10-9eda883dd984?alt=media&token=e0626601-e2d8-462a-90cf-d6fff9229e8d",
    chain: "avalanche",
    telegramURL: "Telegram URL",
    instagramURL: "Instagram URL",
    votes: 0,
    promoted: false,
    youtubeURL: "Youtube URL",
    facebookURL: "Facebook URL",
    discordURL: "Discord URL",
    description: "Coin Description",
    coinName: "Coin Name",
    auditURL: "Audit URL",
    twitterURL: "Twitter URL",
    telegramContact: "Telegram for Contact",
    doxxURL: "Doxx URL",
    verified: false,
    symbol: "Coin Symbol",
    id: "rovNxGKQp5rJd3ZtO0gF",
  },
  {
    symbol: "Coin Symbol",
    youtubeURL: "Youtube URL",
    doxxURL: "Doxx URL",
    telegramContact: "Telegram for Contact",
    coinName: "Coin Name",
    redditURL: "Reddit URL",
    votes: 0,
    email: "smartjeremy01@gmail.com",
    websiteURL: "Website URL",
    discordURL: "Discord URL",
    promoted: false,
    description: "Coin Description",
    presale: true,
    verified: false,
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2F117041814.jpeged3d62bf-2a11-4b42-851e-04f69d37ec62?alt=media&token=28f11543-8ab5-47b0-83fd-c73b680b9f92",
    facebookURL: "Facebook URL",
    safuURL: "SAFU URL",
    twitterURL: "Twitter URL",
    auditURL: "Audit URL",
    instagramURL: "Instagram URL",
    chain: "avalanche",
    contractAddress: "Contract Address",
    kycURL: "KYC URL",
    telegramURL: "Telegram URL",
    id: "ryDlJbUlqwI6PVBrKguS",
  },
  {
    websiteURL: "Website URL",
    telegramURL: "Telegram URL",
    redditURL: "Reddit URL",
    chain: "avalanche",
    kycURL: "KYC URL",
    coinName: "Coin Name",
    contractAddress: "Contract Address",
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/bullishmarketcap-ffbe0.appspot.com/o/smartjeremy01%40gmail.com%2FCoin%20Name%2Fbright-abstract-background-orange-color-free-vector.jpegf445bb61-137d-4975-957b-51b8cd5a33b5?alt=media&token=14658680-56c9-4000-8495-d46f0685c00c",
    promoted: false,
    discordURL: "Discord URL",
    description: "Coin Description",
    verified: false,
    votes: 0,
    email: "smartjeremy01@gmail.com",
    safuURL: "SAFU URL",
    telegramContact: "Telegram for Contact",
    presale: true,
    twitterURL: "Twitter URL",
    symbol: "Coin Symbol",
    facebookURL: "Facebook URL",
    doxxURL: "Doxx URL",
    auditURL: "Audit URL",
    instagramURL: "Instagram URL",
    youtubeURL: "Youtube URL",
    id: "waqesB3aEbijv1a516p9",
  },
];
